import type { RiderLang } from "../store/useStore";

/** Everything the rider sees, in plain words, in three languages. */
const t = {
  next: { en: "Next home", mr: "पुढचं घर", hi: "अगला घर" },
  done: { en: "done", mr: "झाली", hi: "हो गए" },
  left: { en: "left", mr: "बाकी", hi: "बाकी" },
  homes: { en: "homes", mr: "घरं", hi: "घर" },
  delivered: { en: "Delivered", mr: "दिलं", hi: "दे दिया" },
  problem: { en: "Problem", mr: "अडचण", hi: "समस्या" },
  call: { en: "Call", mr: "फोन", hi: "फ़ोन" },
  map: { en: "Map", mr: "नकाशा", hi: "नक्शा" },
  listen: { en: "Listen", mr: "ऐका", hi: "सुनें" },
  takeEmpty: { en: "Take empty bottles", mr: "रिकाम्या बाटल्या घ्या", hi: "खाली बोतलें लें" },
  whatProblem: { en: "What happened?", mr: "काय झालं?", hi: "क्या हुआ?" },
  doorLocked: { en: "Door locked", mr: "दार बंद", hi: "दरवाज़ा बंद" },
  itemBad: { en: "Item short or broken", mr: "माल कमी / फुटला", hi: "सामान कम / टूटा" },
  noWant: { en: "Customer said no", mr: "ग्राहक नको म्हणाले", hi: "ग्राहक ने मना किया" },
  noAddress: { en: "Can't find home", mr: "घर सापडलं नाही", hi: "घर नहीं मिला" },
  cancel: { en: "Cancel", mr: "रद्द", hi: "रद्द" },
  undo: { en: "Undo", mr: "परत", hi: "वापस" },
  saved: { en: "Saved", mr: "नोंद झाली", hi: "दर्ज हो गया" },
  allDone: { en: "All homes done!", mr: "सगळी घरं झाली!", hi: "सारे घर हो गए!" },
  goBack: { en: "Go back to the hub with the empty bottles.", mr: "रिकाम्या बाटल्या घेऊन हबवर परत या.", hi: "खाली बोतलें लेकर हब वापस आएं." },
  allHomes: { en: "All homes", mr: "सगळी घरं", hi: "सारे घर" },
  close: { en: "Close", mr: "बंद करा", hi: "बंद करें" },
  hubSays: { en: "Message from hub", mr: "हबचा संदेश", hi: "हब का संदेश" },
  ok: { en: "OK", mr: "ठीक आहे", hi: "ठीक है" },
  earnToday: { en: "Today's earning", mr: "आजची कमाई", hi: "आज की कमाई" },
  bottles: { en: "Empty bottles", mr: "रिकाम्या बाटल्या", hi: "खाली बोतलें" },
  onTime: { en: "On time", mr: "वेळेवर", hi: "समय पर" },
  perHome: { en: "per home", mr: "प्रति घर", hi: "प्रति घर" },
  perBottle: { en: "per bottle", mr: "प्रति बाटली", hi: "प्रति बोतल" },
  bonus: { en: "Bonus when all homes are done", mr: "सगळी घरं झाल्यावर बोनस", hi: "सारे घर होने पर बोनस" },
  flagged: { en: "Problem", mr: "अडचण", hi: "समस्या" },
  stop: { en: "Stop", mr: "थांबा", hi: "स्टॉप" },
  helpLine: { en: "Call hub", mr: "हबला फोन", hi: "हब को फ़ोन" },
  doneShort: { en: "Done", mr: "झाली", hi: "हो गए" },
  leftShort: { en: "Left", mr: "बाकी", hi: "बाकी" },
  problemShort: { en: "Problem", mr: "अडचण", hi: "समस्या" },
  finishBy: { en: "Finish by 6:15", mr: "६:१५ पर्यंत संपवा", hi: "6:15 तक पूरा करें" },
  atThisSpeed: { en: "At this speed you finish at", mr: "या वेगाने तुम्ही संपवाल", hi: "इस रफ़्तार से आप पूरा करेंगे" },
  onTrack: { en: "On time", mr: "वेळेत", hi: "समय पर" },
  runningLate: { en: "Running late", mr: "उशीर होतोय", hi: "देर हो रही है" },
  minLeft: { en: "min left", mr: "मिनिटं बाकी", hi: "मिनट बाकी" },
  minLate: { en: "min late", mr: "मिनिटं उशीर", hi: "मिनट देर" },
  stepLoad: { en: "Load", mr: "भरा", hi: "लोड" },
  stepDeliver: { en: "Deliver", mr: "वाटा", hi: "बांटें" },
  stepReturn: { en: "Return", mr: "परत द्या", hi: "लौटाएं" },
  loadTitle: { en: "Load your crate", mr: "क्रेट भरा", hi: "क्रेट भरें" },
  loadSub: { en: "Tap each item once it is in the crate", mr: "क्रेटमध्ये ठेवल्यावर प्रत्येक वस्तूवर टॅप करा", hi: "क्रेट में रखने के बाद हर सामान पर टैप करें" },
  spares: { en: "with 2 spare", mr: "२ जास्तीसह", hi: "2 अतिरिक्त के साथ" },
  startDelivering: { en: "Start delivering", mr: "वाटप सुरू करा", hi: "डिलीवरी शुरू करें" },
  startShort: { en: "Start and tell hub what's short", mr: "सुरू करा, कमी माल हबला कळवा", hi: "शुरू करें, कम सामान हब को बताएं" },
  crateLoaded: { en: "Crate loaded", mr: "क्रेट भरलं", hi: "क्रेट भरा" },
  checkCrate: { en: "Check crate", mr: "क्रेट तपासा", hi: "क्रेट जांचें" },
  short: { en: "short", mr: "कमी", hi: "कम" },
  returnTitle: { en: "Return to hub", mr: "हबवर परत या", hi: "हब लौटें" },
  returnBottles: { en: "Empty bottles to hand over", mr: "द्यायच्या रिकाम्या बाटल्या", hi: "सौंपने वाली खाली बोतलें" },
  returnSpares: { en: "Spare items to give back", mr: "परत द्यायचा जास्तीचा माल", hi: "लौटाने वाला अतिरिक्त सामान" },
  handOver: { en: "Hand over", mr: "सुपूर्द करा", hi: "सौंप दें" },
  shiftDone: { en: "Shift complete", mr: "आजचं काम पूर्ण", hi: "आज का काम पूरा" },
  handedAt: { en: "Handed over at", mr: "सुपूर्द केले", hi: "सौंपा गया" },
  newShift: { en: "Next delivery morning (demo)", mr: "पुढची सकाळ (डेमो)", hi: "अगली सुबह (डेमो)" },
  gaveTitle: { en: "How many did you give?", mr: "किती दिलं?", hi: "कितना दिया?" },
  gaveSub: { en: "Press − for what you could not give", mr: "जे देता आलं नाही त्यासाठी − दाबा", hi: "जो नहीं दे पाए उसके लिए − दबाएं" },
  giveRest: { en: "Give the rest", mr: "बाकीचं द्या", hi: "बाकी दे दें" },
  gaveNone: { en: "Nothing given", mr: "काहीच दिलं नाही", hi: "कुछ नहीं दिया" },
  notGiven: { en: "not given", mr: "दिलं नाही", hi: "नहीं दिया" },
  thisWeek: { en: "This week", mr: "या आठवड्यात", hi: "इस हफ़्ते" },
  payday: { en: "Paid on", mr: "पगार", hi: "भुगतान" },
  today: { en: "Today", mr: "आज", hi: "आज" },
  close2: { en: "Done", mr: "झालं", hi: "हो गया" },
} as const;

export type RiderKey = keyof typeof t;
export const tr = (k: RiderKey, l: RiderLang) => t[k][l];
export const speechLang: Record<RiderLang, string> = { en: "en-IN", mr: "mr-IN", hi: "hi-IN" };
